const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, DB=path.join(__dirname,'data.json');
const FRACTIONS=['Правительство','ФСБ','МВД г.Лыт','МВД г.Южный','Воинская часть','Больница','СМИ','Ореховская ОПГ','Курганская ОПГ','Кавказская ОПГ','ФСИН'];
const LEADER=['Заместитель','Лидер'];
const ADMIN=['КУРАТОР','ЗГС ОПГ','ЗГС ГОС','ГС ОПГ','ГС ГОС','Старший администратор','ЗГА','ГА','Рук.проекта'];
const sessions=new Map();
function id(){return crypto.randomUUID()} function hash(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.pbkdf2Sync(p,s,120000,32,'sha256').toString('hex')} function ok(p,h){let [s,v]=h.split(':');return hash(p,s).split(':')[1]===v}
function load(){if(fs.existsSync(DB))return JSON.parse(fs.readFileSync(DB));let d={users:[],news:[],events:[],tasks:[],norms:[],logs:[]};let login=process.env.ADMIN_LOGIN||'admin',pass=process.env.ADMIN_PASSWORD||'ChangeMe123!';d.users.push({id:id(),login,name:login,password:hash(pass),type:'admin',role:'Рук.проекта',fraction:'',avatar:'',warnings:0,blocked:false});d.news.push({id:id(),title:'Добро пожаловать в Good Mobile',text:'Панель лидеров, заместителей и администрации запущена.',date:new Date().toISOString(),author:'Система'});fs.writeFileSync(DB,JSON.stringify(d,null,2));return d} let db=load();
function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2))} function safe(u){let x={...u};delete x.password;return x} function log(a,t='',e=''){db.logs.unshift({id:id(),action:a,target:t,extra:e,date:new Date().toISOString()});db.logs=db.logs.slice(0,500);save()}
function user(req){let c=req.headers.cookie||'',m=c.match(/sid=([^;]+)/);return m?sessions.get(m[1]):null} function auth(req,res){let u=user(req);if(!u||u.blocked){json(res,401,{error:'Не авторизован'});return null}return u} function admin(req,res){let u=auth(req,res);if(!u)return null;if(u.type!=='admin'){json(res,403,{error:'Нужны права администрации'});return null}return u}
function json(res,code,data){let b=Buffer.from(JSON.stringify(data));res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length});res.end(b)}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>4e6)reject(Error('Слишком большой запрос'))});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function sendFile(res,p,type){let b=fs.readFileSync(p);res.writeHead(200,{'Content-Type':type});res.end(b)}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.json':'application/json'};
async function route(req,res){let u=new URL(req.url,'http://x'),p=u.pathname;
try{
if(req.method==='GET'&&p==='/api/config')return json(res,200,{projectName:'Good Mobile',fractions:FRACTIONS,leaderRoles:LEADER,adminRoles:ADMIN});
if(req.method==='POST'&&p==='/api/login'){let x=await body(req),a=db.users.find(v=>v.login.toLowerCase()===String(x.login||'').toLowerCase());if(!a||a.blocked||!ok(String(x.password||''),a.password))return json(res,401,{error:'Неверный логин или пароль'});let sid=id();sessions.set(sid,a);res.writeHead(200,{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`,'Content-Type':'application/json'});return res.end(JSON.stringify({user:safe(a)}))}
if(req.method==='POST'&&p==='/api/logout'){let u=user(req);let c=req.headers.cookie||'',m=c.match(/sid=([^;]+)/);if(m)sessions.delete(m[1]);res.writeHead(200,{'Set-Cookie':'sid=; Max-Age=0; Path=/'});return json(res,200,{ok:true})}
let me=auth(req,res);if(!me)return;
if(req.method==='GET'&&p==='/api/me')return json(res,200,{user:safe(me)});
if(req.method==='GET'&&p==='/api/people')return json(res,200,db.users.filter(x=>x.type==='leader'&&!x.fired).map(safe));
if(req.method==='GET'&&p==='/api/admins'){if(!admin(req,res))return;return json(res,200,db.users.filter(x=>x.type==='admin').map(safe))}
if(req.method==='PUT'&&p==='/api/profile'){let x=await body(req);if(x.login&&db.users.some(v=>v.id!==me.id&&v.login.toLowerCase()===String(x.login).toLowerCase()))return json(res,400,{error:'Логин занят'});if(x.login!==undefined)me.login=String(x.login).slice(0,40);if(x.name!==undefined)me.name=String(x.name).slice(0,40);if(x.avatar!==undefined)me.avatar=String(x.avatar).slice(0,2000000);save();return json(res,200,{user:safe(me)})}
if(req.method==='GET'&&p==='/api/news')return json(res,200,db.news);if(req.method==='GET'&&p==='/api/events')return json(res,200,db.events);if(req.method==='GET'&&p==='/api/norms')return json(res,200,db.norms);if(req.method==='GET'&&p==='/api/tasks')return json(res,200,db.tasks.filter(t=>me.type==='admin'||!t.fraction||t.fraction===me.fraction));
if(req.method==='GET'&&p==='/api/logs'){if(!admin(req,res))return;return json(res,200,db.logs.slice(0,200))}
if(req.method==='POST'&&p==='/api/news'){if(!admin(req,res))return;let x=await body(req);let n={id:id(),title:String(x.title||'').slice(0,100),text:String(x.text||'').slice(0,2000),date:new Date().toISOString(),author:me.login};if(!n.title||!n.text)return json(res,400,{error:'Заполните поля'});db.news.unshift(n);save();log('Создание новости',n.title);return json(res,200,n)}
if(req.method==='POST'&&p==='/api/events'){if(me.type!=='admin'&&me.type!=='leader')return json(res,403,{error:'Нет прав'});let x=await body(req),n={id:id(),title:x.title,description:x.description,date:x.date,author:me.login};db.events.unshift(n);save();return json(res,200,n)}
if(req.method==='POST'&&p==='/api/tasks'){if(!admin(req,res))return;let x=await body(req),n={id:id(),title:x.title,description:x.description,fraction:x.fraction||'',deadline:x.deadline||'',status:'Новая'};db.tasks.unshift(n);save();return json(res,200,n)}
if(req.method==='POST'&&p==='/api/norms'){if(!admin(req,res))return;let x=await body(req),n={id:id(),title:x.title,text:x.text,fraction:x.fraction||''};db.norms.unshift(n);save();return json(res,200,n)}
if(req.method==='POST'&&p==='/api/admin/users'){if(!admin(req,res))return;let x=await body(req);if(!x.login||!x.password||!ADMIN.includes(x.role))return json(res,400,{error:'Заполните поля'});if(db.users.some(v=>v.login.toLowerCase()===x.login.toLowerCase()))return json(res,400,{error:'Логин занят'});let n={id:id(),login:x.login,name:x.login,password:hash(x.password),type:'admin',role:x.role,fraction:'',avatar:'',warnings:0,blocked:false};db.users.push(n);save();log('Создание администратора',n.login,n.role);return json(res,200,{user:safe(n)})}
if(req.method==='POST'&&p==='/api/leader/users'){if(!admin(req,res))return;let x=await body(req);if(!x.login||!x.password||!FRACTIONS.includes(x.fraction)||!LEADER.includes(x.role))return json(res,400,{error:'Заполните поля'});if(db.users.some(v=>v.login.toLowerCase()===x.login.toLowerCase()))return json(res,400,{error:'Логин занят'});let n={id:id(),login:x.login,name:x.login,password:hash(x.password),type:'leader',role:x.role,fraction:x.fraction,avatar:'',warnings:0,blocked:false};db.users.push(n);save();log('Создание лидера',n.login,n.fraction);return json(res,200,{user:safe(n)})}
if(req.method==='PATCH'&&p.startsWith('/api/admin/people/')){if(!admin(req,res))return;let n=db.users.find(v=>v.id===p.split('/').pop());if(!n)return json(res,404,{error:'Не найден'});let x=await body(req);if(x.action==='block')n.blocked=true;if(x.action==='unblock')n.blocked=false;if(x.action==='warning')n.warnings=(n.warnings||0)+1;if(x.action==='setFraction'&&FRACTIONS.includes(x.fraction))n.fraction=x.fraction;if(x.action==='setLeader'){n.type='leader';n.role=LEADER.includes(x.role)?x.role:'Лидер';if(FRACTIONS.includes(x.fraction))n.fraction=x.fraction;n.blocked=false;n.fired=false}if(x.action==='setAdmin'&&ADMIN.includes(x.role)){n.type='admin';n.role=x.role;n.fraction='';n.blocked=false}if(x.action==='fire')n.fired=true;save();log(x.action,n.login);return json(res,200,{user:safe(n)})}
if(req.method==='DELETE'&&p.startsWith('/api/admin/users/')){if(!admin(req,res))return;let idd=p.split('/').pop();if(idd===me.id)return json(res,400,{error:'Нельзя удалить себя'});db.users=db.users.filter(v=>v.id!==idd);save();return json(res,200,{ok:true})}
if(req.method==='DELETE'&&p.startsWith('/api/news/')){if(!admin(req,res))return;db.news=db.news.filter(v=>v.id!==p.split('/').pop());save();return json(res,200,{ok:true})}
if(req.method==='DELETE'&&p.startsWith('/api/events/')){if(!admin(req,res))return;db.events=db.events.filter(v=>v.id!==p.split('/').pop());save();return json(res,200,{ok:true})}
if(req.method==='DELETE'&&p.startsWith('/api/norms/')){if(!admin(req,res))return;db.norms=db.norms.filter(v=>v.id!==p.split('/').pop());save();return json(res,200,{ok:true})}
if(req.method==='GET'){let f=path.join(__dirname,'public',p==='/'?'index.html':p);if(fs.existsSync(f))return sendFile(res,f,mime[path.extname(f)]||'text/plain')}
json(res,404,{error:'Not found'});
}catch(e){console.error(e);json(res,500,{error:'Ошибка сервера'})}}
http.createServer(route).listen(PORT,()=>console.log('Good Mobile panel on '+PORT));
